### ISSUE TITLE
Add carousel slider component

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_freeflow#3]
Please create and add carousel component:
https://tailwindcomponents.com/component/carousel-slider-with-tailwindcss-and-jquery

Add new component to:
- [x] FreeFlow Home page
- [x] examplesite home page

Make sure:
- [x] carousel slider takes the whole home screen 
- [x] goes as background for navbar (navbar - transparent with white font)
- [x] component has automated slide switch as well as can be switched by clicking on the circles on the bottom
- [x] apply to carousel component images from .psd file shared on telegram
- [x] font across whole website is **Gotham Fonts Family**  (see comment: https://github.com/threefoldfoundation/www_freeflow/issues/9#issuecomment-869180894)

Should look like this:

![freeflow_mockup](https://user-images.githubusercontent.com/20182572/123516084-3fddc580-d692-11eb-8d0d-eda54dc49bfd.png)

**Comment by ehab-hassan** [comment]
@Vilnite please send the PSD file 
there is no PSD file sent at telegram just Ai for principles

**Comment by samaradel** [comment]
https://github.com/threefoldfoundation/www_freeflow/issues/9#issuecomment-869180894

**Comment by Vilnite** [comment]
Comment from designer about specific font in titles:
"So what I think it could work is to use a svg file when screen size is mobile.. 
so in those cases we can get rid of the box and use only the font in svg... I'm sending an .ai file with the vectors and you can use them to make the changes on the design according to the screen size."

P.s. I've shared font .ai file on telegram

**Comment by ehab-hassan** [comment]
still have problem with Svg because it not in specific place it change every time and we working with loop, So what I can do is make it image with text on it at mobile with the font effect like this
![bg1_mobile](https://user-images.githubusercontent.com/10484295/123945597-9f8fe580-d99e-11eb-9027-dc6c61d9cb25.jpg)
but that mean any update at text need to be done from photoshop

**Comment by ehab-hassan** [comment]
@Vilnite massages at last 4 images are repeated need the right one so I can put it at images
