### ISSUE TITLE
Make sure principles on home page works well

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_freeflow#9]
I've added all the content but need to make sure it looks well.

- [x] font across whole website is **Gotham Fonts Family** (see comment below)
- [x] Image followed by header text is centred in the middle of the page for each principle

Should look like this:

![freeflow_mockup](https://user-images.githubusercontent.com/20182572/123516062-20df3380-d692-11eb-9162-48b4e9edbdb1.png)

**Comment by ehab-hassan** [comment]
we need to use google font because embedded font not working with gridsome at production as we test it before at io and farming
